### ISSUE TITLE
Mysql columns with no options are skipped

### ISSUE THREAD

**Issue by eeggenberger** [nixys/nxs-data-anonymizer#30] opened 2024-07-24 13:02 UTC
A column in a CREATE TABLE statement that looks like this will be skipped:

```
  `body_summary` longtext,
```

Looks like dhCreateTableColumnAdd doesn't account for such cases, where there's just a type, but no options to it.

**Comment by borisershov** [comment] 2024-09-05 08:34
Hi! Yes, the bug is confirmed. Thanks for the PR, but I think the best way to solve the issue is to switch to regex instead of string comparison. This bug will be fixed in next release

**Closed** 2024-09-20 10:24 UTC
Labels: bug
