### ISSUE TITLE
MySQL CONSTRAINT field treated as a column

### ISSUE THREAD

**Issue by flou** [nixys/nxs-data-anonymizer#14] opened 2024-01-31 13:44 UTC
With the following dump generated with mysqldump (or mariadb-dump):
```sql
-- file: data.sql

CREATE TABLE `employees` (
  `employee_id` INT PRIMARY KEY,
  `first_name` VARCHAR(50),
  `last_name` VARCHAR(50),
  `department_id` INT,
  KEY `idx_last_name` (`last_name`),
  CONSTRAINT `fk_department` FOREIGN KEY (`department_id`) REFERENCES `departments`(`department_id`)
);

INSERT INTO `employees` VALUES
(1, 'John', 'Doe', 101),
(2, 'Jane', 'Smith', 102),
(3, 'Michael', 'Johnson', 101);
```
and the following filter configuration:
```yaml
# file: nxs-config.yaml

filters:
  employees:
    columns:
      first_name:
        value: "REDACTED"
      last_name:
        value: "REDACTED"
```

I get the following error `mismatch count of columns and values for table 'employees'`:
```
{"level":"info","msg":"program started","time":"2024-01-31T14:40:57+01:00"}
CREATE TABLE `employees` (
  `employee_id` INT PRIMARY KEY,
  `first_name` VARCHAR(50),
  `last_name` VARCHAR(50),
  `department_id` INT,
  KEY `idx_last_name` (`last_name`),
  CONSTRAINT `fk_department` FOREIGN KEY (`department_id`) REFERENCES `departments`(`department_id`)
);

INSERT INTO `employees` VALUES
{"level":"error","msg":"anonymizer routing error: fsm read data handler: mismatch count of columns and values for table 'employees'","time":"2024-01-31T14:40:57+01:00"}
{"level":"info","msg":"anonymizer routine done","time":"2024-01-31T14:40:57+01:00"}
{"exit code":1,"level":"info","msg":"program terminating","time":"2024-01-31T14:40:57+01:00"}
```

It seems like nxs-data-anonymizer is treating the CONSTRAINT field as a column in the table definition and it breaks the anonymisation process.

**Comment by borisershov** [comment] 2024-02-07 14:12
Hi! Thanks for your report!

> It seems like nxs-data-anonymizer is treating the CONSTRAINT field as a column in the table definition and it breaks the anonymisation process.

Yes, this is the cause of the problem you described. So I have already fixed the problem locally and new version will be released after testing (till the end of the week)

**Comment by borisershov** [comment] 2024-02-09 12:08
Hi! Please check a fixes for your problem in [version v1.3.1](https://github.com/nixys/nxs-data-anonymizer/releases/tag/v1.3.1).

**Comment by flou** [comment] 2024-02-09 17:14
Seems like it is working fine, thank you!

**Comment by borisershov** [comment] 2024-02-12 06:42
Hi! Nice ))

**Closed by borisershov** 2024-02-12 06:42 UTC
Labels: bug
